[project]
name = "integration"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "opencv-python>=4.11.0.86,<4.12.0",
    "numpy==1.26",
    "pydantic>=2.0",
    "PyYAML>=6.0",
    "python-dotenv>=0.21.0",
    "loguru>=0.7.3",
    "paho-mqtt>=1.6.1",
    "smart-workflow @ git+https://github.com/allenshie/smart-workflow.git@b5ef4c4dbab3525a5dc1c5f1c7eb689da5baf6ee",
    "MCMOT",
    "smart-messaging-core==0.1.1",
]

[project.optional-dependencies]
test = [
    "pytest>=8.4.2",
]

[dependency-groups]
dev = [
    "ruff==0.9.10",
]

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]
per-file-ignores = { "tests/test_logging.py" = ["E402"] }

[tool.uv.sources]
MCMOT = { git = "ssh://git@github.com/ChenPingChen/MCMOT.git", rev = "edf55ccb236481c4189f141ae208dcfc7fea9dfa" }
